### ISSUE TITLE
`Assign()` with some data items breaks a process

### ISSUE THREAD

**Issue by keikari** [permaweb/ao#760] opened 2024-06-04 10:57 UTC
Steps to see the issue:
1. Start a new process from aos
2. Type `Assign({Processes = {ao.id}, Message="p0XcdIORttPGrMOjWdiZgKLB_tNAj9jSU3njOH9VP0I"})`
3. Type anything
4. See error `Transaction 'p0XcdIORttPGrMOjWdiZgKLB_tNAj9jSU3njOH9VP0I' not found on gateway`
Steps 3-4 can be repeated. 

Also it doesn't break if using actually non-existing txid, like `aaaaaaORttPGrMOjWdiZgKLB_tNAj9jSU3njOH9Vaaa`
And some existing txids also work, like `hR_l91uXFxjN077TDRmUnC3asi1mDZOo6qCXIBRx5ns`

![2024-06-04_13-54](https://github.com/permaweb/ao/assets/34790748/b4047236-ea6c-4fc1-8a0f-eb210c032e65)

EDIT: Screenshot from MU (actually probably not related to the process breaking)
![2024-06-05_10-56](https://github.com/permaweb/ao/assets/34790748/f239b415-a90c-4735-a003-e27b07b6e21c)

EDIT2: Breaking of process seems to only happen on https://cu.ao-testnet.xyz, but not on locally run CU

**Comment by keikari** [comment] 2024-06-05 09:09
More details:

This item also gives out of bounds error on MU, but doesn't break the process
```
Assign({Processes = {ao.id}, Message='3EsHLtzhLU6nikyJfcfczlPpmp7PKD6L-wRSaVKpnlY'})
```
![2024-06-05_10-55](https://github.com/permaweb/ao/assets/34790748/3f4e087c-eafe-4ca3-9969-31db9381f7a6)

-------------------------

This works as expected(same as above, but with Exclude):
```
Assign({Processes = {ao.id}, Message='3EsHLtzhLU6nikyJfcfczlPpmp7PKD6L-wRSaVKpnlY', Exclude = {"Data","Anchor"}})
```

-----------------------------
This still gives out of bounds error, and breaks the process(same as initial example, but with Exclude):
```
Assign({Processes = {ao.id}, Message='p0XcdIORttPGrMOjWdiZgKLB_tNAj9jSU3njOH9VP0I', Exclude = {"Data","Anchor"}})
```

**Comment by TillaTheHun0** [comment] 2024-06-06 09:52
We are investigating this. The Compute Unit must query the assigned transaction from a Gateway, and potentially its data from Arweave.

What we are seeing is that the Gateway utilized by the CU is not returning certain transactions, and so the CU reasonably concludes that the transaction cannot be found. We are investigating the root cause.

**Comment by TillaTheHun0** [comment] 2024-06-11 21:04
Confirmed that this was a result of a bundle failing to unbundle at the gateway level. They've since retriggered the bundle and successfully unbundled, and are looking at how to make it more stable.

**Comment by TillaTheHun0** [comment] 2024-06-24 15:06
The original issue was an unbundled tx on the gateway, which has since been resolved.

The "memory access out of bounds" error seems to be occurring when the assigned data item is too large to be passed to the WASM. Currently, the ao message is passed to the WASM via pushing it onto the WASM Instance's stack, which has a fixed size set at build time. Depending on the version of `aos` module, the stack size might have been too small to fit the assigned data, thus causing this error.

Newest version of `aos` has a stack size of [41MB](https://github.com/permaweb/ao/pull/814/commits/db6d8996db60f1d420b0385e3a074ad093049014), so that would be the hard limit on Assignments, as of now, for new ao processes. This is a known limitation and we're working on a solution for larger assignments and data.

I am going to close this, as the original issue was resolved, and the memory access error is a known limitation and is on the roadmap to resolve.

Please let me know if i'm misunderstanding, and I can re-open. Thanks.

**Closed by TillaTheHun0** 2024-06-24 15:06 UTC
Labels: bug
